<?php
/**
 * class.futurama.php 
 * treefiddy futurama quotes module
 * @author Evan Brown <evan@bcin.net>
 */
/**
 * futurama quotes module
 * @author Evan Brown <evan@bcin.net>
 */
class futurama implements module {
    /**
     * futurama module constructor
     * registers the action handler for SmartIRC
     * @param Net_SmartIRC $irc
     * @param modules $modules
     */
    public function __construct(Net_SmartIRC &$irc, modules &$modules, config &$config)
    {
        $irc->registerActionhandler(SMARTIRC_TYPE_CHANNEL, '^!futurama', $modules->modules['futurama'], 'futurama');
    }
    /**
     * sends quote to channel
     *
     * @param Net_SmartIRC $irc
     * @param Net_SmartIRC_data $data
     */
    public function futurama(Net_SmartIRC &$irc, Net_SmartIRC_data &$data) 
    {
	    $quotes = array(
		    'Fry: Space, it seems to go on and on forever. But then you get to the end and a gorilla starts throwing barrels at you.',
		    'Fry: It\'s the future! My parents, my coworkers, my girlfriend. I\'ll never see any of them again! [pause] Wahooo!',
		    'Leela: [to Fry] Well at least here you\'ll be treated with dignity. Now strip naked and get on the probulator.',
		    'Fry: Whoa.a real live robot; or is that some kind of cheesy New Year\'s costume? Bender: Bite my shiny metal ass.',
		    'Fry: Why would a robot need to drink? Bender: I don\'t need to drink. I can quit anytime I want! burp',
		    'Fry: This is awesome! Are we gonna fly through space fighting monsters and teaching alien women to love? Professor Farnsworth: If by that you mean transporting cargo, then yes!',
		    'Fry: I\'m never gonna get used to the 31st century. Caffeinated bacon? Baconated grapefruit? Admiral Crunch? Leela: Well, if you don\'t like that, try some Archduke Chocula.',
		    'Fry: I used to dream about being an astronaut. I just never had the grades. Or the physical endurance. Plus I threw up a lot and nobody liked spending a week with me. Leela: A week would be a bit much.',
		    'Leela: Look, I don\'t know about any of your previous captains, but I intend to do as little dying as possible.',
		    'Amy: Leela\'s gonna kill me. Bender: No, she\'ll probably make me do it.',
		    'Bender: Come on! It is just like making love. You know, left, down, rotate 62 degrees, engage rotor... Amy: I know how to make love!',
		    'Leela: If the oxygen holds out, we might live long enough to starve to death.',
		    'Bender: Fine. I\'ll go build my own lunar lander! With blackjack! And hookers! In fact, forget the lunar lander! And the blackjack! Ah, screw the whole thing.',
		    'Professor Farnsworth: Oh, how awful. Did he at least die painlessly? To shreds, you say. Well, how is his wife holding up? To shreds, you say.',
		    'Bender: Of all the friends I\'ve had. You\'re the first.',
		    'Bender: Beneath that warm, fuzzy exterior beats the cold, mechanical heart of a robot.',
		    'Bender: I don\'t know. I\'ve got a lot of great memories of my old place. [He opens his chest cavity and presses a button.] Bender: And now they\'re gone!',
		    'Fry: Hey, Professor, great jerky! Professor Farnsworth: My God, this is an outrage! I was going to eat that mummy!',
		    'Zapp Brannigan: Captain\'s journal. Stardate.uh. Kif: April thirteenth. Zapp Brannigan: April thirteenth.point two. We have failed to uphold Brannigan\'s Law. However, I did make it with a hot alien babe. And in the end, is that not what man has dreamt of since first he looked up at the stars? [pause] Kif, I\'m asking you a question!',
		    'Zapp Brannigan: You see, Killbots have a preset kill limit. Knowing their weakness, I sent wave after wave of my own men at them, until they reached their limit and shut down.',
		   'Leela: Look, that\'s Zapp Brannigan\'s ship. Fry: Wow, the Zapp Brannigan? Leela: Uh huh. Fry: Who\'s the Zapp Brannigan?', 
		   'Zapp Brannigan: Kif, I have made it with a woman. Inform the men.',
		   'Kif: Shall I fire on them now, sir? Zapp Brannigan: Not yet, Kif. In the game of chess, you can never let your adversary see your pieces.',
		   'Leela: Look, last night was a mistake. Zapp Brannigan: A sexy mistake. Leela: No, just a regular mistake.',
		   'Leela: They say Zapp Brannigan single-handedly saved the Octilian system from a horde of rampaging killbots. Fry: Wow. Bender: A grim day for robot-kind. Ah, but we can always build more killbots.',
		   'Zapp Brannigan: As my protégé, you should know that the only way to deal with a female adversary is to seduce her. [Kif sighs.] Zapp Brannigan: This time we are sure she\'s a woman, right? Kif: [exasperated] Yes!',
		   'Bender: Death to humans! Fry: Aww, it\'s good to hear his voice.',
		   'Fry: We\'re rescuing ya. Bender: I don\'t want to be rescued. Fry: Say what? Bender: I love this planet! I\'ve got wealth, fame, and access to the depths of sleaze that those things bring.',
		   'Bender: You humans think that robots are just machines made to make people\'s lives easier. Fry: Well aren\'t they? Bender: I\'ve never made anyone\'s lives easier and you know it!',
		   'Professor Farnsworth: They say madness runs in our family. Some even call me mad! And why? Because I dared to dream .of my own race of atomic monsters! Atomic supermen with octagonal-shaped bodies that suck blood out of.',
		   'Amy: Guh! It\'s Mom, the world\'s most huggable industrialist.',
		   'Leela: Fry, you can\'t just sit here in the dark listening to classical music. Fry: I could if you hadn\'t turned on the light and shut off my stereo.',
		   'Mom: Now I\'m off to some charity BS for knocked-up teenage sluts.',
		   'Fry: That\'s the saltiest thing I\'ve ever eaten.and I once ate a big heaping bowl of salt! Bender: Oh, come on! That food was fine! The salt content was 10% less than a lethal dose! Dr. Zoidberg: Uh oh. I shouldn\'t have had seconds.',
		   'Leela: Uh, Professor, are we even allowed in the Forbidden Zone? Professor Farnsworth: Why, of course! It\'s just a name, like the Death Zone or the Zone of No Return. All the Zones have names like that in the Galaxy of Terror.',
		   'Leela: This is my first visit to the Galaxy of Terror and I\'d like it to be a pleasant one.',
		   'Telephone voice: Collect call from. Bender: I\'m not giving my name to a machine! Leela: I\'ll accept.',
		   'Dr. Zoidberg: Why don\'t I use a centrifuge to separate out the denser liquid of His Highness? Fry: Won\'t that crush my bones? Dr. Zoidberg: Oh, right. With the bones. I always forget about the bones.',
		   'Fry: It\'s just like the story of the grasshopper and the octopus. All year long, the grasshopper kept burying acorns for winter, while the octopus mooched off his girlfriend and watched TV. But then the winter came, and the grasshopper died, and the octopus ate all his acorns and also he got a racecar. Is any of this getting through to you?',
		   'Fry: What the hell is that? Emperor Bunt: It\'s the Juice-O-Matic 4000. It\'ll strain my juices from you while filtering out the pulp. By which I mean, your shredded remains. Dr. Zoidberg: Of course! Why didn\'t I think of that?',
		   'Fry: This can\'t be happening! Bender: It can and, for all you know, it is.',
		   'Morbo: In lighter news, the city of New New York is doomed. Blame rests with known human professor Hubert Farnsworth and his tiny, inferior brain.',
		   'Professor Farnsworth: Good news, everyone. Tomorrow you\'ll be making a delivery to Ebola 9, the virus planet. Hermes: Why can\'t they go today? Professor Farnsworth: Because tonight\'s a special night, and I want all of you to be alive.',
		   'Professor Farnsworth: I was inventing things when you were barely turning senile!',
		   'Professor Farnsworth: I daresay that Fry has discovered the smelliest object in the known universe! Bender: Ooh, name it after me!',
		   'Video Narrator: New York City: The year 2000. The most wasteful society in the history of the galaxy and it was running out of places to empty its never-ending output of garbage. The landfills were full. New Jersey was full.',
		   '[After watching an online movie on the solution to the garbage problem in New York.] Fry: Wow, you got that off the Internet? In my day, the Internet was only used to download pornography. Professor Farnsworth: Actually, that\'s still true. [In the movie] Female Scientist(stripping): Now that the, uh, garbage ball is in space, Doctor, perhaps you can help me with my sexual inhibitions? Male Scientist(also stripping): With gusto.',
		   'Mayor Poopenmeyer: I now award you with the Academy Prize, which was confiscated from Dr. Wernstrom after it became apparent that he was a jackass.',
		   'Bender: Hey, what kinda party is this? There\'s no booze and only one hooker.',
		   'Bender: Hey! Do I preach to you when you\'re lying stoned in the gutter? No! So beat it! Fry: Who was that guy? Bender: Your Mamma! Now shut up and drag me to work!',
		   '[Fry, Leela and Bender are at a Beastie Boys\' concert] Leela: Impressive! They\'re laying down mad rhymes with an 80% success rate. Bender: I believe that qualifies as "ill".at least from a technical standpoint. Fry: Would you guys shut up? I\'m trying to look cool!',
		   'Leela: Who would have thought Hell would really exist? And that it would be in New Jersey? Fry: Actually.',
		   'Leela: what happens if we lose? Robot Devil: You\'ll only get a smaller silver fiddle, and I guess I\'ll kill one of you. [He points at Fry.] Robot Devil: "him" [Fry gasps.] Leela: We\'ll do it. [Fry gasps.]',
		   'Fry: Do you know how to play the fiddle? Leela: No. But I used to play the drums, they\'re sorta similar.',
		   'Fry: But wouldn\'t a golden fiddle weigh hundreds of pounds and sound crummy? Robot Devil: Well, it\'s mostly for show. [holds up a twinkling golden fiddle]',
		   'Bender: You guys go on without me! I\'m going to go look for more stuff to steal! Fry: You\'re going back for the Countess, aren\'t you? Bender: Oh, all right, I am. But if anything happens to me, tell them I was robbing some dead guy! Fry: I\'ll tell them you went down prying the wedding ring from his cold, dead fingers. Bender: I love you, buddy!',
		   'Leela: Oh, god.not Zapp Brannigan. Dr. Zoidberg: You know Zapp Brannigan? Leela: Let\'s just say we crossed paths. Bender: Was that before or after you slept with him?',
		   'Countess de la Roca: Bender, I don\'t care whether you have money. I love you for your artificial intelligence and your sincerity simulator.',
		   'Kif: Captain, may I have a word with you? Zapp Brannigan: No! Kif: It\'s an emergency, sir. Zapp Brannigan: Come back when it\'s a catastrophe!',
		   'Kif: Do you remember that "course correction" you made, sir? Zapp Brannigan: No. Kif: Well it\'s proving somewhat more suicidal than we initially hoped.',
		   'Leela: Oh my God! We\'re heading straight into a black hole! Fry: Talk about a mood killer.',
		   'Zapp Brannigan: Don\'t blame yourself, Kif. We were doomed from the start. Nothing remains now but for the captain to go down with his ship. Kif: Why that\'s surprisingly noble of you, sir. Zapp Brannigan: No. It\'s noble of you, Kif. As of now, you\'re in command.',
		   'Countess de LaRoca: Bender, you risked your life to save me! Bender: And I\'d do it again! And perhaps a third time! But that would be it.',
		   'Fry: Back in the 20th century we had no idea there was a university on Mars. Professor Farnsworth: Well, in those days Mars was a dreary uninhabitable wasteland much like Utah; but unlike Utah, Mars was eventually made livable.',
		   'Fatbot: I heard that in one single night, you drank a whole keg, streaked across campus and crammed 58 humans into a phone booth. Bender: Yeah, well, a lot of them were children.',
		   'Dean Vernon: Whenever a fire alarm is pulled, it\'s Robot House. Whenever the campus liquor store is looted, Robot House. Every time a human corpse is desecrated. Bender: -uh, I can explain that- Dean Vernon: That\'s enough out of you! From this day forth, Robot House is on dodeca-tuple secret probation!',
		   '[Prof. Farnsworth and Fry are trying to help Gunther choose between his IQ-expanding hat and a regular life as a monkey.] Professor Farnsworth: Come on, Gunther. Take the hat! Fry: No, the banana. The banana! Professor Farnsworth: Consider the philosophical and metaphysical ramifications of the. Fry: Banana, banana, banana!',
		   'Professor Farnsworth: But what about your super intelligence? Gunther: When I had that, it was too much pressure to use it. All I want out of life is to be a monkey of moderate intelligence who wears a suit. Thats why I\'ve decided to transfer to business school. Professor Farnsworth: Noooooooo!',
		   'Professor Farnsworth: Oh, I always feared he might run off like this. Why, why, why didn\'t I break his legs?',
		   'Gearshift: Hey, Bender, you sure this is a shortcut? Bender: Not as sure as I was an hour ago!',
		   'Zapp Brannigan: Stop exploding, you cowards!',
		   'Zapp Brannigan: When I\'m in command, every mission\'s a suicide mission!',
		   'Zapp Brannigan: Call me cocky, but if there\'s an alien out there I can\'t kill I haven\'t met him and killed him yet. But I can\'t go in alone. That\'s why I\'m ordering every available ship to report for duty. Anyone without a ship should secure a weapon and fire wildly into the air.',
		   'Zapp Brannigan: If we can hit that bull\'s-eye, the rest of the dominoes will fall like a house of cards. Checkmate!',
		   'Zapp Brannigan: We\'re all from different cultures here. Some of you are white, and some of you are black. You\'re brown. And you\'re silver. But I don\'t care if your skin\'s red, or tan, or Chinese. You\'re all going to have to learn to die together.',
		   'Zapp Brannigan: The key to victory is discipline, and that means a well made bed. You will practice until you can make your bed in your sleep. Fry: You mean while I\'m sleeping in it? Zapp Brannigan: You won\'t have time for sleeping soldier, not with all the bed making you\'ll be doing.',
		   'Zapp Brannigan: Good work everyone; the mothership is destroyed. [The real mothership reveals itself.] Zapp Brannigan: What the hell is that thing? Kif: It appears to be the mothership. Zapp Brannigan: Then what did we just blow up? Kif: [checks one of the instruments] The Hubble Telescope.',
		   'Amy Wong: There aren\'t any copies left. Professor Farnsworth: No, there wouldn\'t be... most videotapes from that era were damaged in 2443, during the second coming of Jesus.',
		   'Leela: I have never seen anyone so addicted to Slurm. Fry: This is nothing. Back in high school I used to drink a hundred cans of cola a week. Yep, right up until my third heart attack.',
		   'Professor Farnsworth: Who are those horrible orange creatures over there? Glermo: Why, those are the Grunka-Lunkas! They work here in the Slurm factory. Professor Farnsworth: Tell them I hate them.',
		   'Fry: Uh, could I have some Slurm please? Glermo: No food or drink allowed on the tour. You\'ll have to wait until you\'re partying with Slurms McKenzie. Fry: When will that be? Glermo: Soon enough. Fry: That\'s not soon enough!',
		   'Glermo: Hey, I didn\'t pay you to sing. You just used up today\'s bathroom break! Grunka Lunka: Hardass. Glermo: I heard that.',
		   'Leela: Hey, what\'s behind that door? Glermo: Nothing. Leela: Is it the secret ingredient? Grunka Lunkas: Grunka Lunka dunkity dingredient, you should not ask about the secret ingredient. Bender: Okay, okay! We get the point! Leela: I was just curious because of the armed guards. Grunka Lunkas: Grunka Lunka dunkity darmed guards. Bender: Shut the hell up!',
		   'Fry: Fine! I\'ll let go and swim around in the Slurm and drink as much as I want. Hehehe. [Fry falls into the Slurm.] Fry: Help! I can\'t swim!',
		   'Fry: My God! What if the secret ingredient.is people!? Leela: No, there\'s already a soda like that. Soylent Cola. Fry: Oh. How is it? Leela: It varies from person to person.',
		   'Glermo: There will be no further questions! Fry: Why?',
		   'Fry: Hey, what are these rings in Nibbler\'s fang? Vet: Hmm. I\'m still a little woozy from a gazelle kick this morning, but if he\'s anything like the common tree, the rings might indicate his age. Fry: Heheh, yeah, well. Good luck. It\'d take some kind of genius to count all those rings. Vet: He\'s 5.',
		   'Amy: Bender! How could you flush Nibbler down the toilet? Bender: Well, step one: I had to lift the seat. That was the first little annoyance.',
		   'Leela: How would you feel if I flushed Fry down the toilet? Bender: Only one way to find out.',
		   'Leela: There\'s no such thing as mutants. That\'s a ridiculous urban myth. Professor Farnsworth: Oh, don\'t be so sure. Many scientists believe humans really could mutate down there, due to exposure to toxic waste, and radioactive runoff, and good old American feces. Fry: God bless America.',
		   'Dwayne: Don\'t worry. We\'re harmless! Raoul: I have three arms. Dwayne: I said "harmless." Not "armless." Vyolet: Lay off him. You know he\'s only got one ear.',
		   'Bender: You guys realize you live in a sewer, right? Dwayne: Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! Leela: No. We\'re on the top. Fry: Daylight and everything. Vyolet: It must be wonderful. Bender: Meh.',
		   'Bender: Hey, I got a busted ass here, I don\'t see anyone kissing it! Dr. Zoidberg: Alright, I\'m coming.',
		   'Bender: Hey, what the hell are you doing with my head?! Professor Farnsworth: I need to tinker in it. Bender: Then why don\'t you just use a potted plant, like Fry?',
		   'Bender: My God, I\'m overcomed with... feelings! I\'m experiencing a powerful yearning to... to cram my gullet full of mackerel heads. Dr. Zoidberg: That\'s me, baby.',
		   'Bender: Now I\'m worried that I\'m not as smart as Leela, but at the same time I feel relief that I\'m cuter than her. Amy: Uh, that\'s me. Fry: Thanks for covering.',
		   'Fry: Wow! You guys worship an unexploded nuclear bomb? Vyolet: Yeah, but nobody\'s that observant. It\'s mainly a Christmas and Easter thing.',
		   'Leela: I love every living creature. Fry: Even me? Leela: As a friend. Fry: Damn.',
		   'Grand Councilwoman Glab: What are your thoughts on this momentous occasion, Your Neutralness? Neutral President: I have no strong feelings one way or the other.',
		   'Zapp Brannigan: What makes a man turn neutral? Lust for gold? Power? Or were you just born with a heart full of neutrality?',
		   'Zapp Brannigan: I hate these filthy neutrals, Kif! With enemies, you know where they stand, but with neutrals.who knows. It sickens me.',
		   'Zapp Brannigan: Throw her in the brig. Fry: We don\'t have a brig. Zapp Brannigan: Then throw her in the laundry room, which will hereafter be referred to as the brig.',
		   'Zapp Brannigan: One day a man has everything. The next day he blows up a 400 billion dollar space station. And the next day he has nothing. It makes you think. Kif: No, it doesn\'t.',
		   'Zapp Brannigan: My friends! You can take away a man\'s title and his uniform but you can never take away his integrity or his honor. Plus it was mostly Kif\'s fault.',
		   'Zapp Brannigan: All I need from a crew is their complete loyalty. If I had that then they could drink beer in their underpants for all I care. Bender: Beer!? Fry: Underpants!?',
		   'Zapp Brannigan: So, a plot to assassinate a weird looking alien with scissors. How very neutral of you. But everybody knows that rock beat scissors. But paper beats rock. And scissors beats paper! Kif, we have a conundrum. [Kif sighs.] Zapp Brannigan: Search them for paper. And while you\'re at it, go get a rock. Kif: Why?',
		   'Morbo: Morbo congratulates our gargantuan cyborg president. May death come quickly to his enemies!',
		   'Bender: Game\'s over, losers! I have all the money! Compare your lives to mine and then kill yourselves!',
		   'Richard Nixon\'s Head: Hello Morbo, how\'s the family? Morbo: Belligerent and numerous. Richard Nixon\'s Head: Good man. Nixon\'s pro-war and pro-family.',
		   'Fry: Why would Nixon stay at the Watergate? Leela: They give you a discount if you\'ve been here before.',
		   'Bender: Ah, yes! John Quincy Adding Machine. He struck a chord with the voters when he pledged not to go on a killing spree. Professor Farnsworth: But, like most politicians he promised more than he could deliver.',
		   'Fry: Professor, when did you become so obsessed with voting? Professor Farnsworth: The very instant I became old.',
		   'George Washington: So telleth, Bender, what hath happened to your body? Bender: I hocked it. George Washington: Hocked it? Why wouldst thou do that? Bender: Same reason you hocked your teeth. George Washington: Ah, booze money.',
		   'Gerald Ford\'s Head: Frankly, I\'ve never found voting to be that necessary to the process. Richard Nixon\'s Head: No kidding, Ford!',
		   'Nixon\'s Head: Well listen here missy, computers may be twice as fast as they were in 1973, but your average voter is as drunk and stupid as ever. The only one who\'s changed is me! I\'ve become bitter and let\'s face it, crazy over the years!',
		   'Bender: Let\'s face it, comedy\'s a dead art form. Tragedy, now that\'s funny.',
		   'Fry: This snow is beautiful. I\'m glad global warming never happened. Leela: Actually, it did. But thank God nuclear winter canceled it out.',
		   'Robot Santa: You DARE bribe Santa?! I\'m going to shove coal so far up your stocking, you\'ll be coughing up diamonds!',
		   'Professor Farnsworth: Dear God, they\'ll be killed on our doorstep! And there\'s no trash pickup until January 3rd.',
		   'Robot Santa: You\'ve all been very, very naughty indeed! Except you, Dr. Zoidberg. This is for you! Dr. Zoidberg: A pogo stick! Robot Santa: As for the rest of you, I\'m going to tear off your skin like wrapping paper and deck the halls with your guts!',
		   'Bender: I\'m very generous. What about that time I gave blood? Fry: Whose blood? Bender: Eh, some guy\'s.',
		   'Linda: Is there anything sadder than homeless robots at Xmas? Only drowning puppies, and there would have to be a lot of them.',
		   'Fry: Now that\'s what I call a thousand years of progress: a Bavarian Cream dog that\'s self-microwaving!',
		   'Dr. Zoidberg: Hmm, this love intrigues me. Teach me to fake it!',
		   'Dr. Zoidberg: It\'s all so complicated with the flowers and the romance and the lies upon lies!',
		   'Dr. Zoidberg: I\'m confused Fry. I\'m feeling things I\'ve never felt before. Is it love when you care about the female for reasons beyond mating? Fry: Nope, must be some weird alien emotion.',
		   'Fry: Ask her about her day. Dr. Zoidberg: Why would I want to know about that? Fry: You wouldn\'t, but ask anyway.',
		   'Dr. Zoidberg: Now Fry, it\'s been a few years since medical school so remind me; disembowling in your species.fatal or non-fatal? Fry: Fatal. [Dr. Zoidberg hands money to Bender, who is taking bets from audience members.] Dr. Zoidberg: Large bet on myself in round 1!',
		   'Bender: It\'s always so sad when a friend goes crazy and you have to have a big clam bake and cook him. Yeehaw!',
		   'Voice on T.V.: Is modern day life making you angry and impatient? Bender: Shut the hell up and get to the point!',
		   'Bender: Oww, I think I got whiplash. Leela: You can\'t have whiplash, you don\'t even have a neck! Bender: I mean ass whiplash.',
		   'Bob Barker: Garbage! Human garbage!',
		   'Bob Barker: Do you brain dead space jockeys have any idea how much that thing is worth? Fry: $100,000? Leela: $200,000? Bender: $200,001? Bob Barker: [to Leela] You\'re closest without going over.',
		   'Fry: Bender?! You stole the atom. Bender: I can explain. It\'s very valuable.',
		   'Professor Farnsworth: Everyone get in bed with me. I have something to show you. [The Planet Express staff climbs into the bed.] Professor Farnsworth: Feast your eyes.on this! [Everyone gasps.] Leela: It\'s beautiful! Amy Wong: And huge! Fry: Can I touch it?',
		   'Fry: I\'m so confused. The Bender I liked turned out to be evil, and the Bender I hated was good. How can I live my life when I can\'t tell good from evil? Bender: They\'re both fine choices, whatever floats your boat.',
		   'Fry: I just made out with that radiator woman from the Radiator Planet! Leela: Fry, that\'s a radiator. Fry: Oh. Is there a burn ward within ten feet of here?',
		   'Leela: Valentine\'s day\'s coming up. Fry: Oh crap! I forgot to get a girlfriend again!',
		   'Amy: Lucky I\'m a member of the Austro-Afro-Antarctico-Amer-Asian Auto Association. Hello, Septuple-A?',
		   'Fry: Hey, tell me something. You\'ve got all this money. How come you always dress like you\'re doing your laundry? Amy: I guess because my parents keep telling me to be more ladylike. As though. Fry: I\'ve been there. My folks were always on me to groom myself and wear underpants. What am I, the pope? Amy: Yeah, and if you were the pope they\'d be all, "Straighten your pope hat." And "Put on your good vestments."',
		   'Bender: Congratulations Fry, you\'ve snagged the perfect girlfriend. Amy\'s rich, she\'s probably got other characteristics. Leela: Bender! Romance isn\'t about money! Bender: Oh, so it\'s just coincidence that Zoidberg here is desperately poor and miserably lonely? Please! Leela: For your information, it\'s because he\'s hideous! Dr. Zoidberg: Awww.',
		   'Fry: I\'m doing my job, there\'s Amy. I spend a few hours selecting a candy from the machine, there\'s Amy. I wake up the morning after sleeping with Amy, there\'s Amy!',
		   'Fry: All of a sudden, she\'s talking about hanging out, hanging out, she\'s getting way too serious, I\'m not a one woman man, Leela. Leela: I\'m sure you\'ll be back to zero soon enough.',
		   'Sal: Whoa! Nice eyeball, Eyeball. Leela: Nice ass, Ass.',
		   'Bender: Ah, computer dating. It\'s like pimping, except you rarely use the phrase "upside your head".',
		   'Dr. Zoidberg: You\'re both very lucky. I\'d pay anything to end my miserable loneliness. If only I weren\'t so desperately poor! Bender: Wait. You mean people will pay good money for romance? Hmm. I think I have a scheme so deviously clever that I. [Cut to Bender in a courtroom.] Judge: $500 and time served! Bender: Stupid anti-pimping laws!',
		   'Professor Farnsworth: Good news, everyone! I\'ve taught the toaster to feel love!',
		   'Leela: Bender, let\'s hit the gym. I\'m going to teach you to fight like a girl. Bender: [In low, menacing tones] I\'ll put on my tutu.',
		   'Wrestling Promoter: You\'ll soon be the least popular wrestler since Sergeant Feces Processor!',
		   'Amy: Fry, where\'s your brain slug? Professor Farnsworth: [picks up a withered brain slug] Poor little guy starved to death.',
		   'Fry: I always thought it was real like pro wrestling but it\'s fixed like boxing.',
		   'Bender: [To Leela] Bender the Offender doesn\'t need you! Bender the Offender doesn\'t need anybody! Floozie: What about us, Mr. the Offender? Bender: Well, obviously I need floozies.',
		   'Master Phnog: You were an excellent student. Too bad I was a lousy teacher!',
		   'Fry: Well, thanks to the Internet, I\'m now bored with sex. Is there anywhere that panders to my lust for violence? Bender: Is the Space Pope reptilian?',
		   'Computer: Leela, you\'ve got mail! Leela: [dejected] Oh. Computer: It\'s not spam!',
		   'Bender: Behold, the internet. Fry: My God, it\'s full of ads!',
		   '[Bender is disguised as a sexy nurse, talking to a chat room participant.] Bender: Hi, I\'m a naughty nurse, and I really need someone to talk to. $9.95 a minute. Chat room participant: Oh, you\'re a dollar naughtier than most. [He hands Bender the money.] Bender: So, how \'bout them Knicks?',
		   'Fry: Psst! Leela! You\'ve got to get me out of here! It\'s horrible! Eating scraps; letting my waste drop wherever it falls, like an animal in a zoo! Leela: Animals go in the corner. Fry: The corner! Why didn\'t I think of that?',
		   'Preacherbot: Do you, Leela, copy and paste his response, \'til death do you part?',
		   'Leela: Where did you get that couch? And that TV? And all this stuff? Alkazar: They were giving it away on a street corner. Just like you, Leela! Leela: Too bad they weren\'t giving away the three things you really need: mouthwash, a back wax and stain-proof underwear. Alkazar: By the way, your friend Fry fell into the dungeon. Take him a taco so he doesn\'t die and stink up the place. Leela: Oh, come on Al, can\'t you let the little guy out? Alkazar: Twice in one day? I\'m not Superman, you know!',
		   'Professor Farnsworth: Good news, everyone! The university is bringing me up on disciplinary charges. Wait! That\'s not good news at all!',
		   'Professor Farnsworth: Everyone\'s always in favor of saving Hitler\'s brain, but when you put it in the body of a great white shark, ooooh, suddenly you\'ve gone too far!',
		   'Professor Farnsworth: Everyone, I have a very dramatic announcement. So anyone with a weak heart should leave now. Goodbye! [walks out]',
		   'Professor Farnsworth: And this is my universal translator. Unfortunately so far it only translates into an incomprehensible dead language. Cubert: Hello! Universal Translator: Bonjour! Professor Farnsworth: Crazy jibberish!',
		   'Professor Farnsworth: Goodbye, cruel world. Goodbye, cruel lamp. Goodbye, cruel velvet drapes, lined with what would appear to be some sort of cruel muslin and the cute little pom-pom curtain pull cords. Cruel though they may be, I.',
		   '[The ship is under attack and Professor Farnsworth, unconscious, is the only one who can repair the engines.] Leela: We have to wake him up. [Leela shakes the professor, Fry blows an air horn at him, and Bender throws water on his face.] Fry: [to Bender] Try shocking him. Bender: Your Social Security check is late! Stuff costs more than it used to! Young people use curse words! Fry: Damn it! He\'s not waking up.',
		   '[Hermes is threatening to jump off a building.] Planet Express Crew: No! Don\'t jump! Bender: Do a flip!',
		   'Hermes: Life. death. either way I\'ll be confined to a tiny cubicle!',
		   'Hermes: Curse that Dr. Zoidberg. If I get out of here, he\'ll be looking down the business end of a shrimp fork!',
		   'Fry: What\'s with the specs, Bender? Bender: They\'re my lucky shades! I stole \'em off some lucky man while his lucky seein\'-eye dog was takin\' a whiz!',
		   'Professor Farnsworth: Damn it Hermes, jump already! Quit hogging that healthy liver.',
		   'Number 1.0: Don\'t quote me regulations! I co-chaired the committee that reviewed the recommendation to revise the color of the book that regulations are kept in! (darkly) We kept it grey.',
		   'Number 1.0: Bureaucrat Conrad, you are technically correct - the best kind of correct.',
		   'Number 1.0: Congratulations indeed, but you finished with two seconds to spare so I\'m demoting you. A good bureaucrat never finishes early.',
		   'Hermes: Exciting news, people! The pet license I requisitioned for Nibbler has arrived. Leela: Hermes, that\'s sweet. I didn\'t know you cared about Nibbler. Hermes: Dream on, woman. I\'d like to put the little bastard in a sack and toss the sack in a river and hurl the river into space. But I do like filling out requisitions and these were some doozies! [Hermes opens the envelope.] Hermes: Great Jah\'s dreadlocks! There\'s been a mix-up: This isn\'t a pet license, it\'s a fishing license! And it\'s mandatory!',
		   '[Fry is presented with an egg-sized pill which will allow him to withstand the pressure underwater.] Fry: Are you crazy? I can\'t swallow that. Professor Farnsworth Well, then good news! It\'s a suppository.',
		   '[The Planet Express Ship is being dragged underwater by a colossal mouth bass.] Leela: Depth at forty five hundred feet. Forty eight hundred. Fifty hundred. Five thousand feet. Professor Farnsworth: Dear Lord, that\'s over 150 atmospheres of pressure. Fry: How many atmospheres can this ship withstand? Professor Farnsworth: Well it\'s a spaceship, so I\'d say anywhere between zero and one.',
		   'Leela: Where\'s Fry? Bender: I didn\'t kill him. Professor? Professor Farnsworth: No, I\'ve been busy.',
		   'Fry: You know what I like best about you, Umbriel? You find me fascinating, even when I\'m not claiming to be a jewel thief or a lion tamer. Umbriel: Lions? There are sea lions on the land? Fry: Yep, we call them land-sea lions. I tame them.',
		   'Amy: What happened to my parasol? Bender: Beats me, it wasn\'t there when I took your umbrella.',
		   'Professor Farnsworth: He may have Ocean Madness, but that\'s no excuse for Ocean Rudeness!',
		   'Supplicant: Please, Don-Bot.look into your hard drive, and open your mercy file! Don-Bot: File not found.',
		   'Cop: He\'s making a break for it. Get him! Fry: No, no, I was just picking my nose. Cop: He\'s picking his nose. Get him!',
		   '[Leela is temporarily blind] Amy: Leela, a little help is nothing to be embarassed about. Like, maybe I could do your makeup. Leela: I don\'t need help. For your information, I did this all by myself. [turns to reveal horribly crooked lipstick and mascara on right side of face] Professor Farnsworth: You look beautiful. Incidentally, my favorite artist is Picasso.',
		   'Don-Bot: Alright, let\'s mafia things up a bit. Joey, burn down the ship. Clamps, burn down the crew.',
		   'Clamps: It\'s gonna be clamp this, clamp that, badda-climp badda-clamp!',
		   'Professor Farnsworth: Good news, everyone! There\'s a report on TV with some very bad news!',
		   'Slurm Soda Machine: I\'ve got a big big thirst for human blood!',
		   'Fry: Ya, I\'d like some coffee please. Coffee Machine: Would you like cream in your coffee? Fry: Yes please. Coffee Machine: Out of cream! Would you like sugar in your coffee? Fry: Yes, eight spoons please. Coffee Machine: Out of coffee! Fry: Leela, I think the coffee machine\'s broken! [The machine squirts coffee at Fry.] Coffee Machine: How do you like me now?!',
		   'Greeting Card: Come comrade Bender, let us take to the streets! Bender: Is it the boring peaceful kind of taking to the streets? Greeting Card: No. The violent kind, with looting, and possibly starting a few fires.',
		   'Bender: Hey, a six-pack of strawberry champagne! Don\'t mind if I help myself! Greeting Card: No, Comrade Bender! Liquor is the opiate of the human bourgeoisie! Bender: What? Greeting Card: In the glorious Robot Workers\' Paradise, there will be no liquor! Only efficient synthetic fuels! Bender: No liquor!? Do svidaniya, comrade.',
		   'Mom: Conquer Earth, you bastards! Robot crowd: Conquer Earth, us bastards!',
		   'Fry: They\'re like sex, except I\'m having them!',
		   'Fry: I\'m experienced with foraging. I used to find edible mushrooms on my bath mat!',
		   'Leela: Well, it\'s a Type M planet. So it should at least have Roddenberries.',
		   'Fry: Hey, business is great! Bender: Ehh, great is okay, but amazing would be great.',
		   'Professor Farnsworth: There\'s one way and only one way to determine if an animal is intelligent. Dissect its brain!',
		   'Leela: Come on, little Poppler. Say mama! Fry: Look, Leela. Even if you\'ve heard one talk, that doesn\'t mean it\'s intelligent. I mean, parrots talk. And we eat them, right? Bender: Yeah! Maybe it just learned to talk as a parlour trick. Like Fry. Fry: Like Fry! Like Fry!',
		   'Bender: Yes! I\'m gonna be rich! [looks at Fry] You too, but it\'s hard to get excited about that.',
		   'Bender: Hear me! Hear me! Stop eating Popplers! Stop eating them with honey mustard sauce! Stop eating them with tangy sweet and sour sauce! Stop eating the new Fiesta Poppler Salad! Stop taking advantage of the money-saving twelve-pack! Stop enjoying Popplers on the patio, in the car, or on the boat, wherever good times are had!',
		   'Bender: They\'re tasty, right? Let\'s call them Tastycles.',
		   'Professor Farnsworth: You\'ve killed me! Oh, you\'ve killed me! Leela: Oh God, what have I done? Professor Farnsworth: I just told you! You\'ve killed me!',
		   'Hermes: What are you hacking off? Is it my torso?! It is! My precious torso!',
		   'Bender: Blackmail\'s such an ugly word. I prefer extortion. The ex- makes it sound cool.',
		   'Fry: What if Bender was really giant? Leela: You idiot! We already saw that. Fry: I know. I liked it. I want to see it again. Professor Farnsworth: We are not seeing it again! Ask something less stupid! Fry: Um. What if I never fell into that freezer-doodle and came to the future-jiggy? Professor Farnsworth: That question is less stupid; though you asked it in a profoundly stupid way.',
		   'Nichelle Nichols: Killing him isn\'t working and that\'s all we\'re good at!',
		   'Al Gore: You fool! You foolish fool!',
		   '[After the Universe is destroyed, everyone floats around in a white void.] Fry: Where are we? Al Gore: I don\'t know. But I can darn sure tell you where we\'re not. The Universe! Nichelle Nichols: Eternity with nerds. It\'s the Pasadena Star Trek convention all over again!',
		   'Professor Farnsworth: That story was preposterous. Steven Hawking in a pizzeria. This thing isn\'t worth the gold it\'s made of.',
		   'Professor Farnsworth: Now, be careful, Fry. And if you kill anyone, make sure to eat their heart to gain their courage. Their rich, tasty courage.',
		   'Soldier: Why is this godforsaken planet worth dying for? Zapp Brannigan: Don\'t ask me. You\'re the one who is going to be dying.',
		   'Zapp Brannigan: Now, like all great plans, my strategy is so simple an idiot could have devised it.',
		   'Zapp Brannigan: Fry, I am demoting you. Kif, what\'s the most humiliating job? Kif: Being your assistant. Zapp Brannigan: Wrong! Being your assistant!',
		   'Zapp Brannigan: Men, you\'re lucky men. Soon you\'ll all be fighting for your planet. Many of you will be dying for your planet. A few of you will be forced through a fine mesh screen for your planet. They will be the luckiest of all.',
		   'Richard Nixon\'s head: We are now in position over Spheron 6. This is the moment we have been training for all yesterday afternoon.',
		   'Richard Nixon\'s head: Hold on there, Starsky! I\'m up to something here. I want this robot fixed. Fixed like Kennedy fixed the 1960 election! Damn bean-eating war hero!',
		   'Soldier: This is the worst part. The calm before the battle. Fry: And then the battle\'s not so bad? Soldier: Oh right. I forgot about the battle.',
		   'Bender: I can\'t keep running people over. I\'m not famous enough to get away with it.',
		   'Bender: And until then, I can\'t die? Fortune-Telling Robot: Who said that? Of course you can die! You want to die?! Bender: No! I want to live! There\'s still too many things I don\'t own!',
		   'Uncle Vladimir: Come, Bender. You\'ll like being dead! Bender: That\'s what they said about being alive!',
		   'Fry: Poor Bender, you\'re seeing things. You\'ve been drinking too much. Or too little. I forget how it works with you. Anyway, you haven\'t drunk exactly the right amount.',
		   'Calculon: The year was 2019 and I was just a lowly robot arm working in an automotive research lab. I was working on Project Satan. A savage and intelligent military vehicle built from the most evil parts of the most evil cars in all the world. The steering wheel from Hitler\'s staff car. The left turn signal from Charles Manson\'s VW. The windshield wipers from that car that played Knight Rider. Fry: Knight Rider wasn\'t evil! Calculon: His windshield wipers were. It didn\'t come up much in the show though. Anyway, only after bringing Project Satan to life did they discover they made a horrible mistake. For you see.it was pure evil.',
		   'Fry: Words. Nothing but sweet, sweet words that turn into bitter orange wax in my ears.',
		   'Amy: Oh no! Someone you know must\'ve died! Bender: I hope it was one of my enemies! Those guys suck.',
		   'Fry: No-one even cared that I was gone! Michelle: Well, one person did. [Fry and Michelle hold hands for a moment.] Fry: Who was it?',
		   'Fry: All right, all right, if it will make you happy, I will overthrow society.',
		   'Michelle: It gave me a chance to think. Fry: I\'m sorry.',
		   'Fry: Things are different this time. Before she was demanding and possessive, but now she wants me to do stuff and stay with her all the time.',
		   'Fry: Michelle, I don\'t regret this, but I both rue and lament it.',
		   'Leela: Monday Monkey lives for the weekend, sir.',
		   'Dr. Zoidberg: Goodbye friends! I\'ll miss you! Good riddance to them. Now Zoidberg is the popular one! Professor Farnsworth: Yes, yes. Let\'s all talk to Zoidberg.',
		   'Fry: I\'ve had it with women. From now on I\'m concentrating on my career. Can I have my old job back? Professor Farnsworth: Why, I\'ve forgotten why I even fired you. Bender: Because he destroyed your business, your home and all your possessions. Professor Farnsworth: Oh yes.get lost! (the Professor pulls a lever which opens a trap door under Fry\'s feet)',
		   'Dr. Zoidberg: So long! I\'m off to toss this old shell in the dumpster, and maybe pick up those potato chips Amy didn\'t finish yesterday! Amy: Those were toenail clippings! Dr. Zoidberg: A feast is a feast!',
		   'Zapp Brannigan: [piloting the orbiting restaurant] She\'s built like a steakhouse, but she handles like a bistro.',
		   'Zapp Brannigan: You win again, gravity!',
		   'Zapp Brannigan: This whole sector is uncharted. Kif: It is not uncharted, you lost the chart!',
		   'Fry: Pff, a female leader? Leela: Fry, shut up. Fry: Yes, captain.',
		   'Femputer: The Amazonians will be divided into three groups. The one called Zapp will be snu-snued by the large women. He that is designated Fry will be snu-snued by the petite women. And Kif, as the most attractive male, will be snu-snued by the most beautiful women of Amazonia. Then the large women. Then the petite women. Then the large women again.',
		   'Fry: Goodbye, friends. I never thought I\'d die like this. But I always really, really hoped.',
		   'Zapp Brannigan: We need rest. The spirit is willing, but the flesh is spongy and bruised.',
		   'Zaff Brannigan: Kif, I\'m headed to the mens room and I\'ll be needing an attendant so- Oh I\'m sorry you\'re crying, like a woman!',
		   'Sal: Hey, sexy mama, let\'s get busy and freaky in that order! Fry: Hey! How would you like it if Leela said you were sexy and she wanted to make love to you? Sal: Eh, I gots five minutes. She looks pretty good for a truck stop chick! Fry: You take that back! She does not look good for a truck stop chick! Sal: Yeah, you\'re right. She don\'t gots enough meat for a guy like me. Fry: She does too! She\'s loaded with meat! She\'s got more meat than a cow!',
		   'Lord Mayor of Colon: You\'ve damaged your brain, universe! But no more than a week of binge drinking or five minutes on a cellphone!',
		   'Professor Farnsworth: If we can stimulate that nerve, the bowel will convulse, expelling the entire worm society. Hermes: But what about the worms in the other parts of his body? Professor Farnsworth: Listen, this is gonna be one hell of a bowel movement. Afterwards he\'ll be lucky if he has any bones left.',
		   'Bender: Sorry you struck out, sausage link. If it\'s any consolation, my life is great! Babes! Bucks! I got it all! Fry: Well, at least I learned Leela\'s a lost cause. I give up. Bender: There you go! [yawns] Goodnight. I gotta get up early to go parasailing with movie stars!',
		   'Fry: It\'s like a party in my mouth and everyone\'s throwing up.',
		   'Professor Farnsworth: Anyhoo, your net-suits will allow you to experience Fry\'s worm infested bowels as if you were actually wriggling through them. Dr. Zoidberg: There\'s no part of that sentence I didn\'t like!',
		   'Hermes: If it keeps up at this rate he\'ll soon be as strong and flexible as Gumby and Hercules combined! Dr. Zoidberg: Gumbercules? I love that guy!',
		   'Professor Farnsworth: If we don\'t get rid of the worms now, they\'ll burrow so deep into the bowel that not even Hermes\' famous Jerk Prunes could dislodge them! Hermes: I call it Caribbean Drano.',
		   'Professer Farnsworth: The nerve is through here. Where\'s Zoidberg? [Zoidberg enters, riding a sperm like a horse] Dr. Zoidberg: Yippie-ki-yay! You\'ll never guess where I\'ve been!',
		   'Fry: Why aren\'t we moving? Leela: I don\'t know! Usually when I do stuff like this, the ship moves!',
		   'Bender: [singing] I should give you all a beating but I really have to fly. Santa: [singing] If I weren\'t stuck here frozen I\'d harpoon you in the eye.',
		   'Bender: Isn\'t it true you that you have been paid for your testimony? Pramala: Yes. You gave me a dollar and some candy. Bender: And yet you haven\'t said what I told you to say! How can any of us trust you?',
		   'Fry: I\'m Santa Claus! Hermes: No, I\'m Santa Claus! Amy: We\'re also Santa Claus! Dr. Zoidberg: And I\'m his friend Jesus. Mayor: None of you are Santa Claus! How dare you lie in front of Jesus!',
		   'Mayor: My god! The real Santa! Get \'im, Jesus! Dr. Zoidberg: [running away] I help those who help themselves!',
		   'Bender: Gee whiz, Santa. You want me to help you? Fry: [to Bender] Don\'t do it! He\'s evil! Santa: I know he is, but I have no choice.',
		   '[Bender is being led past several other robots on his way to his execution.] Smitty: Deactivated robot walking! We\'ve got a deactivated robot walking! Robot: When you see the Robot Devil, tell him I\'m coming! [Bender walks past the next cell, which contains the Robot Devil.] Bender: Hey, that guy told me to tell you. Robot Devil: I heard him!',
		   'Racetrack PA announcer: And the winner is number three, in a quantum finish. Professor Farnsworth: No fair! You changed the outcome by measuring it!',
		   'Fry: That clover helped my rat-fink brother steal my dream of going into space. Now I\'ll never get there! Leela: You went there this morning for donuts.',
		   'Bender: There! Now no one can say I don\'t own John Larroquette\'s spine!',
		   'Bender: Fine, but grab a shovel; I\'m one skull short of a mouseketeer reunion.',
		   'Fry: Hey Leela, how about the kiss for good luck? [Leela sighs and kisses him in the cheek] Fry: I meant tongue-luck.',
		   'Fry: Leela, Bender, we\'re going graverobbing. Bender: I\'ll get my kit!',
		   'Fry: It\'s all lies, every word of it. He wasn\'t original, he wasn\'t a martian, he wasn\'t Philip Fry, and since when is he a "the"? Bender: You\'re twice the "the" he ever was.',
		   'Yancy Fry, Sr.: Yancy, I\'d like you to met your new brother, Philip. Yancy Fry, Jr.: I wanna be called Philip! Me Philip! Me Philip!! Yancy Fry, Sr.: Son, your name is Yancy, just like me and my grandfather and so on: all the way back to Minuteman Yancy Fry - who blasted Commies during the American Revolution.',
		   'Yancy Fry, Jr.: Thanks for lending me your tux for the wedding dad. Yancy Fry, Sr.: Yancy, that tux got me through \'Nam in style.',
		   'Leela: [to Bender] That aerosal head spray makes your antenna smell nice... Bender: Thank you. Leela: ...but it\'s doing long-term damage to the planet. Bender: So? It\'s not like it\'s the only one we\'ve got.',
		   'Professor Farnsworth: Being captain is about intuition and heart. A good captain can\'t have either one. That\'s why cold, logical Bender is perfect for the job. Bender: Well, I do think of human life as expendable.',
		   'Fry: No fair! Leela was training me to be captain. She even let me sit in her lap and steer [pulls out a piece of paper] in this comic I drew. Dr. Zoidberg: Oh, the new one is out!',
		   'Fry: What\'s happening? Dr. Zoidberg: All 6,000 hulls have been breached! Fry: Oh, the fools! If only they\'d built it with 6,001 hulls! When will they learn?',
		   'Hyperchicken: Son, as your lawyer, I declare y\'all are in a 12-piece bucket o\' trouble. But I done struck you a deal: Five hours of community service cleanin\' up that ol\' mess you caused. Bender: Five hours? Aw, man! Couldn\'t you just got me the death penalty?',
		   'Bender: I don\'t know why but when I look down at their little faces, it makes me wanna puke! In a good way!',
		   'Dr. Zoidberg: Captain, I don\'t think we\'re on Pluto anymore. In fact, we may have left space as we know it! Fry: Then where are we? You told me you could navigate! Dr. Zoidberg: [crying] Stop yelling at me!',
		   'Professor Farnsworth: Perhaps it\'s your outlook that needs a good bend, a ninety degree bend to a place where happiness is perpendicular to wonderment.',
		   'Professor Farnsworth: Those delightful birds with their chirp chirp chirp and their tweet tweet splat.',
		   'Fry: Professor, I\'ve never seen you so cheerful. What the hell\'s wrong with you?',
		   '[The crew has discovered that some of their belongings have been bent.] Hermes: Sweet lamprey of Sante Fe! My edge has been bent! Amy: My javelin too! It\'s ruined! Now we\'ll never beat Jupiter State! Zoidberg: My slinky! My cuddly little pet slinky!',
		   'Bender: Sorry I\'m not your lover boy Flexo, whom you love so much. You love any one even pretending to be him! Angleyne: Maybe I love you so much I love you no matter who you are pretending to be. Bender: Oh how I wish I could believe or understand that!',
		   'Donbot: That wad of scab money should be slushin\' my funds and kickin\' my back.',
		   'Joey Mousepad: He\'s flashing his cash loaf again. Donbot: How many times is that? Two or three? Clamps: Three. Donbot: All right. That\'s the necessary number of times. That scab is gonna have a little \'on the job accident\'. Joey Mousepad: With all due respect Don-Bot, I don\'t think we should rely on an accident happening. Let\'s kill him ourselves. [Donbot sighs frustratedly.]',
		   'Professor Farnsworth: My new bent outlook has completely re-energized me. I\'m even dating a young Brazilian retired actress. Fry: Alright! Farnsworth: Some say I\'m robbing the cradle but I say she\'s robbing the grave.',
		   'Bender: You call yourself divorced?! You\'re making a mockery of one of our most honored institutions!',
		   'Nibblonian: They travel from world to world making everyone stupid in order to wipe out all thought in the universe. Leela: Wipe out all thought? My God, they\'re like flying televisions.',
		   'Giant Brain Spawn: Foolish human race! Organizing your knowledge by category just made it easier to absorb. Dewey, you fool! Your decimal system has played right into my hands!',
		   'Morbo: Morbo can\'t understand his teleprompter because he forgot how you say that letter that\'s shaped like a man wearing a hat. Linda: It\'s a \'T\'. It goes \'tuh\'. Morbo: Hello, little man. I will destroy you!',
		   'Female Nibblonian: The Brain Spawn suppress intelligence by attacking the delta brain wave. Every animal and robot in the universe generates this wave, as do certain trees. Nibbler: Fry, however, does not. Female Nibblonian: Somehow he has cobbled together a random assortment of other brain waves into a working mind. Leela: Like a prom dress made from carpet remnants! Nibblonian: Yes, like your prom dress.',
		   'Leela: You go fight biggest brain of all. Fry: Even bigger than those? Holy nuts! Where is it? Leela: I\'ono. Fry: Hmm. A giant brain is basically a giant nerd. And where would a giant nerd be? [gasps] The libary!',
		   'Fiona: Nibblonians to Nibble stations. Prepare Cuddlebutt for deployment in 40 nibblets. Nibbler: Sometimes I fear we are cute. Fiona: Oh, niggle-snoosh.',
		   'Fry: Now he\'s trapped in a book I wrote. A crummy world of plot holes and spelling errors. Giant Brain Spawn: The Big Brain am winning again! I am the greetest! Ha-ha-ha-ha. Now I am leaving Earth for no raisin!',
		   'Leela: You can count on me! Fiona: No we can\'t.',
		   'Humorbot 5.0: So, I said, "Supercollider? I just met her!".',
		   'Professor Farnsworth: I\'ve been a Harold Zoid fan since back when my hips were made of bone.',
		   'Calculon: I\'m programmed to be very busy.',
		   'Calculon: I just pray they like me half as much as I do.',
		   'Calculon: I\'ve seen plagues that had better opening nights than this!',
		   'Bender: Calculon is gonna kill us and it\'s all everybody else\'s fault!',
		   'Dr. Zoidberg: Well, editing is a long and expensive process, but we spent all the money on pies, so.it\'ll be ready Friday.',
		   'Calculon: Nay, I respect and admire Harold Zoid too much to beat him to death with his own Oscar.',
		   '[Bender has just adopted some orphans.] Bender: Kids, meet uncle Fry! Fry: Hey, why are all those kids following you around? D\'you have candy stuck to your ass?',
		   'Fry: But you\'re better than normal: you\'re abnormal.',
		   'Leela: Oh, Adlai, I\'ve had a wonderful time today. No one\'s stared at me, or avoided staring at me, or tried to burn me. You make me feel so not weird. Adlai: Leela, you\'re nine hundred and ninety nine thousand, nine hundred and ninety nine in a million.',
		   'Fry: What\'s so wonderful about Leela being normal? The rest of us aren\'t normal and that\'s what makes us great. Like Dr. Zoidberg: he\'s a weird monster who smells like he eats garbage and does. Dr. Zoidberg: Damn right! Fry: And the Professor\'s a senile, amoral crackpot. [Farnsworth blubbers and waves] Hermes is a Rastafarian accountant. Hermes: Tally me banana! Fry: Amy\'s a klutz from Mars. Amy: [drops her glass] Sploops! Professor Farnsworth: And, Fry, you\'ve got that brain thing. Fry: I already did! So, Leela, do you wanna be like us? Or do you wanna be like Adlai with no severe mental or social problems whatsoever? Leela: That\'s the dumbest question I ever heard!',
		   'Leela: Now take me to the hospital and put my eye back the way it was! Right now! Adlai: Why should I do that? [Leela shoves Adlai against the wall and grabs his collar.] Leela: Listen, buddy. By the end of the day, one of us is gonna have one eye!',
		   'Leela: What are their names? Bender: Kids have names? Orphan: My name is Nina, this is Albert- Bender: -And from now on you\'re all named Bender Jr.',
		   'Orphan: Daddy Bender, we\'re hungry. Bender: What\'s with you kids? Every few days it\'s food, food, food. [pause] Alright, I\'ll get you some stupid food. Orphan: Can we have Bender Burgers again? Bender: No. The cat shelter\'s on to me!',
		   'Amy: Wait! I\'m too rich to be kidnapped!',
		   'Zapp Brannigan: I am the man with no name. Zapp Brannigan, at your service.',
		   'Martian Chief: I am "Singing Wind" chief of the Martians. Zapp Brannigan: Take me to your leader. Martian Chief: .moving along.',
		   'Professor Farnsworth: It sounds dangerous, someone could get killed. Fry, Leela, Bender; I want you to go with them.',
		   'Professor Farnsworth: This mission is incredibly dangerous. Someone\'s sure to be killed. Fry, Leela, Bender. Bender: Damn you, old man!',
		   'Amy: My name\'s Amy Wong. And you are? Martian Chief: Mad at Wong family!',
		   'Zapp Brannigan: (referring to Amy, who is standing right next to him) How do we even know she\'s alive? Amy Wong: I\'m fine. Zapp Brannigan: Shh! You\'re weakening our bargaining position!',
		   'Zapp Brannigan: Chief, my people are people of law. And that law is (pulls a gun) no backsies! Martian Chief: The time for stupid statements is over.',
		   '[The Planet Express staff visit Fry and Bender in The Institute for Criminally Insane Robots.] Professor Farnsworth: Don\'t worry, Fry, I too once spent a nightmarish time in a robot asylum ... but now it\'s nearly over. [Farnsworth leaves.]',
		   'Leela: We\'re all trying to help you. We\'ve petitioned the governor but he doesn\'t want to appear soft on people who\'ve been falsely imprisoned. Fry: At least I have friends on the outside. Bender\'s been no help at all. Bender: Je suis Napoleon! No seriously, I\'m not. Amy: Bender, you should be more ashamed of yourself than usual. Bender: Ah, lighten up honey. I\'m just trying to get through a difficult time using humor.',
		   '[Fry and Bender are encased in a cardboard box, which is being rolled out of the courtroom.] Fry: Ow my head! Ow my feet! Ow my head! Ow my feet! Professor Farnsworth: Keep your chin up. Fry: Ow my chin!',
		   'Amy: Aww, he looks like a little insane drunken angel.',
		   'Hermes: Fry! Don\'t be a hero! It\'s not covered by the health plan!',
		   'Roberto: I\'m thinking of a number between one and ten. If you guess it, you die first! Bender: Ahm... fifty-six...-ish?',
		   'Bender: Don\'t kill me yet! I\'m starting to come down with Stockholm Syndrome.handsome.',
		   'Fry: These robots don\'t believe that I\'m human. How do I convince them? Bender: You can try dropping dead, that\'ll show them. Fry: I don\'t wanna!',
		   'Bender: I guess if you want children beaten, you have to do it yourself.',
		   'Cubert: Hey, Leela, help me apply these flame decals I got in my cereal. They\'ll make the ship go faster. Leela: And what\'s your scientific basis for thinking that? Cubert: I\'m twelve.',
		   'Leela: If you were my kids you\'d get quite a talking to.from your father.when he got home from the Senate. Professor Farnsworth: Oh, brother. What have they done now? Bender: Those pork dumplings sent us on a fake pizza delivery! Fry: The address was on Dogdoo 8 but the universe ends right after Dogdoo 7! Hermes: Child mon, is this true? Dwight: Yeah, but why are you mad at us? Your dummy brigade wasted a week on an obviously fake mission! Cubert: [pointing at Bender] Plus, they\'re making bootleg beer inside company property! Bender: Lies! Lies and slander! Professor Farnsworth: Accusing gentle Bender of a misdeed? Now you\'ve gone too far!',
		   'Dwight: Can I use the gun? Hermes: What kind of a father would I be if I said no?',
		   'Dwight: I heard alcohol makes you stupid. Fry: No I\'m....doesn\'t. Leela: Actually, Dwight, you\'re right. Alcohol is very, very bad. For children. But once you turn twenty-one, it becomes very, very good!',
		   'Amy: Oh, no! My beautiful money!',
		   'Dr. Zoidberg: It\'s toe-tappingly tragic!',
		   'Bender: I was a hero to broken robots, because I was one of them! But how can I sing about being damaged if I\'m not? That\'s like Christina Aguilera singing in Spanish. Wait, that\'s it - I\'ll fake it!',
		   'Bender: So can I keep the money? Art Garfunkel\'s Descendant: Over my dead career.',
		   'Hermes: Way to go Bender. You got mutilated and now you\'re going to be a Folk singer. Both our dreams came true!',
		   'Beck: Now Bender, you can write songs about how you feel. Like when I wrote Devil\'s Haircut I was feeling - what\'s that song about? Bender: Yeah! But I won\'t use any fake words like Odelay! Beck: Odelay is a word! Just look it up in the Becktionary.',
		   'Fry: Drugs are for losers, and hypnosis is for losers with big weird eyebrows.',
		   '[Representatives from the Globetrotter planet challenge Earth to a basketball game.] Fry: What happens if we lose? Bubblegum Tate: Nothing! There\'s nothing at stake, and no threat. Beyond the shame of defeat.',
		   'Marv Albert: This is a dark day for Humanity, folks. We have been beaten...in basketball.',
		   '[A temporal distortion has caused Fry to lose the basketball game.] Leela: Now all the planets are going to start cracking wise about our mothers. Hermes Conrad: [tearfully] I\'m just glad my fat ugly momma isn\'t alive to see this. Professor Farnsworth: Enough about your promiscuous mother, Hermes!',
		   'Fry: Ooh, professor! Pick me! I wanna show Leela my skills! Professor Farnsworth: Hmm. Will said skills pay the bills?',
		   'Professor Farnsworth: Doomsday device? Ah, now the ball\'s in Farnsworth\'s court! [Farnsworth presses a button, revealing an arsenal of doomsday weapons.] Professor Farnsworth: I suppose I could part with one and still be feared.',
		   'Bender: My life, and by extension everyone else\'s, is meaningless.',
		   'Professor Farnsworth: By Tuesday it\'ll be Thursday. By Wednesday, it\'ll be August. And by Thursday, it\'ll be the end of existence as we know it!',
		   'Fry: I still don\'t know what I did to make Leela love me. Hermes: Maybe you\'re just a fantastic lover, Fry. Amy: Um, no.',
		   'TV show character: Why should I believe you? You\'re Hitler!',
		   'Fry: For one brief moment, I felt the heartbeat of creation, and it was one with my own. Amy: Big deal. Bender: We all feel like that all the time.',
		   'Professor Farnsworth: Oh dear! She\'s stuck in an infinite loop, and he\'s an idiot! Well, that\'s love for you.',
		   'Sal: So it\'s always been your dreams to destroy a planet? Fry: Yeah, what have they ever done for me!',
		   'Lucy Liu: Let\'s hide in here. It\'ll add to my box office gross.',
		   'Bender: Humans dating robots is sick. You people wonder why I\'m still single? It\'s \'cause all the fine robot sisters are dating humans! Leela: Bender, this is Fry\'s decision ... and he made it wrong. So it\'s time for us to interfere in his life.',
		   'Lucy Liu(full body): Mister Mayor, if you want to find out who the real vampire is look in a mirror. Mayer:[in movie] I can\'t! I\'m a vampire!',
		   'Fry: My only other dreams are to be invisible in a chocolate factory and to date a celebrity. Bender: I can hit you over the head until you think that\'s what happened.',
		   'Lucy Liu (Robot): I\'ll never forget you... MEMORY DELETED.',
		   'Bender: When will man learn that all races are equally inferior to robots?',
		   'Bender: Hey, you add a one and 2 zeros to that or we walk! Leela: How much did you make me? Bender: One hundred dollars.',
		   'Leela: Strike one! A personal best!',
		   'Bob Uecker: Welcome to Fenway Park, home of the Boston Poindexters, where the Mets close out a season that will rank among mankind\'s most awful crimes.',
		   '[Leela is signing autographs.] Leela: Who am I making this out to? Girl: Ummm.eBay. Leela: That\'s a popular name today. Little "e", big "B"?',
		   'Coach: You\'ve been training with the Hank Aaron? Leela: I\'ve been training with a Hank Aaron.',
		   'Fry: Incredible! This place is just like the ancient Egypt of my day. Slave Driver: That is no coincidence, for our people visited your Egypt thousands of years ago. Fry: I knew it! Insane theories, one; regular theories, a billion. Slave Driver: We learned many things from the mighty Egyptians, such as pyramid-building, space travel and how to prepare our dead so as to scare Abbott and Costello. Fry: Also Wolfman.',
		   'High Priest: Great wall of prophecy, reveal to us God\'s will, that we may blindly obey! Other Priests: Free us from thought and responsibility. High Priest of Osiris IV: We shall read things off you! Other Priests: Then do them. High Priest of Osiris IV: Your words guide us! Other priests: We\'re dumb.',
		   'Leela: This society is a bunch of idiots.',
		   'Random Slave: Pharaoh Bender! He once more walks among the living! Bender: How we doin\'?',
		   'Leela: Bender, we\'re trying our best. Bender: Your best is an idiot!',
		   'Fry: All right.it\'s Saturday night. I have no date, a two liter bottle of Shasta and my all-Rush mix tape. Let\'s rock!',
		   'Voiceover: You watched it! You can\'t unwatch it!',
		   'Bender: Now, you say you\'re off to see the professor? \'Cause I could use a heart. A human heart. I need to pump a lot of blood out of my basement.',
		   'Fry: I know that monkey, his name\'s Donkey. Professor: Monkeys aren\'t donkeys! Quit messing with my head!',
		   'Professor Farnsworth: After all, who needs courage when you have.a gun!',
		   'Fry: Leela, are you alright? You got wanged on the head. Leela: I was having the most wonderful dream. Except you were there, and you were there, and you were there!',
		   'Leela: Why did you bring us here? Dr. Zoidberg: And why did I have to take a cab?',
		   'Leela: There\'s no place like.I want to be a witch!',
		   'Fry: I\'ve never seen a supernova blow up, but if it\'s anything like my old Chevy Nova, it\'ll light up the night sky.',
		   'Bender\'s head: That\'s no flying saucer! That\'s my ass!',
		   'Professor Farnsworth: For example, if you killed your grandfather, you\'d cease to exist! Fry: But existing is basically all I do!',
		   'Fry: We\'re in the middle of nowhere, which is the safest part of nowhere.',
		   'President Truman: Take this to Area 51. Soldier: But sir, that\'s where we\'re building the fake moon landing set. President Truman: Then we\'ll have to REALLY land on the Moon! Invent NASA and tell them to get off their fannies!',
		   'President Truman: Why have you come here? Are you planning on making some alien-human hybrid? Dr. Zoidberg: Are you coming on to me?! President Truman: Hot crackers! I take exception to that! Dr. Zoidberg: I\'m not hearing a \'no\'...',
		   'Professor Farnsworth: Choke on that, causality! Bender\'s head: 1947 can bite my shiny, metal. (Their spaceship hits a bump and Bender\'s head falls out, down to the earth) Bender\'s head: Aaaaaaaaaaaaaaaaaaaassssss!',
		   'Professor Farnsworth: [Fry has chastised the professer about changing history, after he has slept with his grandmother and become his own grandfather.]Ooh, a lesson in not changing history from mister "I\'m-my-own-grandpa"! Let\'s get the hell out of here already! Screw history!',
		   'Dr. Zoidberg: The president is gagging on my gas bladder! What an honor!',
		   'Bender: Oh cruel fate, to be thusly boned. Ask not for whom the bone bones, it bones for thee.',
		   'Bender: Who would have known playing God could have such terrible consequences?',
		   '[Fry and Leela have locked some monks in a laundry room.] Monk: Let us out! We cooked our shoes in the dryer and ate them. Now we\'re bored!',
		   'Bender: You know, I was God once. God: Yes, I saw. You were doing well until everyone died.',
		   'Malakai: I beseech thee, rise up against them, smite someone who deserves it for once.',
		   'Leela: Fry, if I drop dead from exhaustion, make sure my body freezes in a dignified position; none of that huddled over for warmth crap.',
		   'God: It takes a light touch. Like a safecracker, or a pickpocket. Bender: Or a guy who burns down a bar for the insurance money! God: Exactly, if you make it look like an electrical thing.',
		   'God: When you do things right, people won\'t be sure you\'ve done anything at all.',
		   'Bender: I\'ll vote it down like a raise for schoolteachers!',
		   'Steve: What would you say if I said, "I\'m worried about blank"? Fry: Don\'t you worry about blank. You let me worry about blank. Steve: Good. I would have also accepted "Blank? Blank?! You\'re not looking at the big picture!"',
		   'Leela: Fry, we\'re worried about Planet Express. Fry: Don\'t you worry about Planet Express, let me worry about blank.',
		   'Fry: Boneitis? Pft! That\'s a funny name for a horrible disease.',
		   'Fry: So, what\'s the deal? You guys don\'t believe in robot Jesus? Jewish Robot: We believe he was built and that he was a very well programmed robot, but he wasn\'t our Messiah.',
		   'Bender: Fry! Quit doing the right thing, you jerk!',
		   'Leela: Let Mom buy the company. We all want to be filthy stinking rich. Dr. Zoidberg: Trust me. Two out of three doesn\'t cut it.',
		   '[Dr. Zoidberg has broken one of the professor\'s bottles.] Dr. Zoidberg: Oh no! The professor will hit me! But if Zoidberg fixes the bottle.then perhaps gifts!',
		   'Elzar: No, I\'m not teaching you to become a chef. Bender: But I watch your show, you owe me.',
		   '[Dr. Zoidberg runs up to the stage of the full-packed, worldwide-televised Iron Cook stadium.] Dr. Zoidberg: Wait! Everyone must know! I broke the Professor\'s bottled ship, and what is worse, I framed my dearest friend: Fry. [Dr. Zoidberg begins to sob.] Dr. Zoidberg: I can never repay him his ten dollars, so I must take the only honorable path, what with the killing myself. [Zoidberg steals a sword from the presenter, Chairman Koji, and rips open his clothes with his claw.] Dr. Zoidberg: Here I go already, with the killing of myself! [Zoidberg stabs himself with sword, but it only buckles on his shell.] Chairman Koji: Aaah! That sword cost five thousin dolluuu! Dr. Zoidberg: Fry did it! [Zoidberg flees, whooping.]',
		   'Chairman Koji: [to Bender] Domo arigatou, Mr Roboto.',
		   '[The Professor puts the "Essence of pure flavor" in a chemical analyzer.] Professor Farnsworth: Yes, ordinary water, laced with only a few spoonfuls of LSD.',
		   'Hiroki: Aki, what\'s Elzar making? Aki: Well Hiroki-san, when I asked him, he asked what business it was of mine and conjectured that my mother was a prostitute. Martha Stewart: In the English countryside, many prostitutes decorate their rooms with festive gourds.',
		   'Bender: I decline the title of Iron Chef and accept the lesser title of Zinc Saucier, which I just made up, it also comes with double prize money.',
		   '[Amy and Kif are in the Holo-shed. A pony gallops by.] Amy: Spirit! Kif, that\'s the pony I always wanted but my parents said I had too many ponies already. Kif: Yes, I programmed it in for you. Four million lines of BASIC!',
		   'Attila the Hun: Stop! Don\'t shoot fire stick in space canoe! Cause explosive decompression! Zapp Brannigan: Spare me your space age technobabble, Attila the Hun!',
		   'Amy: You trashed my party board? Mrs. Wong: Damn right! Now you\'re a mom, the only surfing you do is under a big wave of responsibility!',
		   'Kif: Amy! Is it you or have I gone crazy with loneliness? Bender: Both!',
		   'Midwife: I will now take my leave of you. I live here, so I won\'t actually be going anywhere, but you don\'t have to talk to me anymore!',
		   'Leela: Everyone who was invited is here. Dr. Zoidberg: Also Zoidberg.',
		   '[In the castle, evil holograms begin to come to life.] Amy: Look, it\'s Spirit! [Spirit, ridden by Attila the Hun, breathes fire] Kif Kroker: And that\'s Professor Moriarty!.Jack the Ripper!.evil Lincoln! Professor Moriarty: Right-ho, gents, it\'s another simulation gone mad, so murder and mayhem, standard procedure. Evil Lincoln: Real holographic-simulated Evil Lincoln is back!',
		   'Fry: I didn\'t ask for a completely reasonable excuse! I asked you to get busy!',
		   'Leela: I usually try to keep my sadness pent up inside where it can fester quietly as a mental illness. Fry: Yeah, I do that with my stupidness.',
		   'Hermes: It looks like toxic waste. And it smells like toxic waste! Fry: What does it taste like? Hermes: Delicious fig pudding! Ooh, that\'s good. But, a distinct aftertaste of toxic waste.',
		   'Fry: Leela, freak out later. We\'re not done escaping yet!',
		   'Mutant: He ruined my wedding dress. Bender: Honey, that dress was ruined the minute it went on you. That\'s what I\'m talking about.',
		   'Fry: Isn\'t that the machine that makes noses? Professor Farnsworth: It can do other things, why shouldn\'t it!',
		   'Professor: You all remember Leela\'s orphanage, right? Fry: Yeah, we talk about it all the time. Leela: Really? Fry: Nope. Burn! [high fives Bender] Professor: Well done fellows.',
		   'Planet Express Ship: Oh honey, look! The Tapirs! It says here that the babies lose their pyjama-like coat after their first year. Isn\'t that interesting, honey? Bender: Yup. Mind-numbingly interesting.',
		   'Dummy #1: Is heaven missing an angel? \'Cause you\'ve got nice cans! Dummy #2: My two favorite things are commitment and changing myself. Leela: Does that dummy have a brother?',
		   '[Lrrr and Ndnd are watching Friends on TV.] Lrrr: This is ancient Earth\'s most foolish program. Why does Ross, the largest friend, not simply eat the other five? Ndnd: Perhaps they are saving that for sweeps.',
		   'Professor Farnsworth: With that big new Romanticorp contract, I\'ve been able to make those government-mandated upgrades you\'ve all been suing me about.',
		   'Leela: Doesn\'t it bother you even a little that you\'re taking advantage of your girlfriend\'s trust? Bender: [laughing] Oh, wait, you\'re serious. Let me laugh even harder.',
		   'Ndnd: [reading a candy heart] What is this emotion you call \'wuv\'? Lrrr: Surely it says \'love\'! Ndnd: No, \'wuv\'! With an earth W! Behold! Lrrr: This concept of "wuv" confuses and infuriates us!',
		   'Planet Express Ship: Bender! I saw you with those two sleazy femmebots at the restaurant! Explain that! Bender: Okay, I like a challenge.',
		   'Planet Express Ship: You\'re just jealous. No one loves you because you\'re tiny and made of meat.',
		   'Leela: Oh, I completely forgot! I left my apartment on fire!',
		   'Professor Farnsworth: Good news, anyone! The Swedish supercollider I ordered came in! .-kea Robot: Enjoy your affordable Swedish crap.',
		   '[Fry and Leela discovered a cream that can cause super-powers, and are seeing which they have.] Leela: Super strength? Fry: Yep. Leela: Lickity speed? Fry: Check. Leela: Ability to command the loyalty of sea creatures? Fry: Hey, Zoidberg, get in here! Dr. Zoidberg: Screw you! Leela: Ain\'t got that. Fry: Nope.',
		   'Leela: Listen up, New New York! There\'s a new group of superheroes in town, and we\'re gonna. Hattie McDougal: Quiet! It\'s 4 AM and I just fell asleep for the first time in thirty years! Leela: Sorry! [whispering] And a new era of justice has begun. Hattie McDougal: What!?',
		   'Fry: Wow! A superpowers drug you can just rub onto your skin? You\'d think it would be something you\'d have to freebase.',
		   'Leela: I feel like I just went ten rounds with Mighty Thor. Fry: I feel like I was mauled by Jesus.',
		   'Teddy Roosevelt\'s Head: A man boxing a kangaroo is a peculiar spectacle. But a kangaroo boxing a robot? Now I\'m afraid you\'ve lost me!',
		   'Nixon\'s Head: My fellow Earthicans, we enjoy so much freedom, it\'s almost sickening. We\'re free to choose which hand our sex-monitoring chip is implanted in, and if we don\'t want to pay our taxes, why, we\'re free to spend a weekend with the Pain Monster. Pain Monster: See ya April 15th, folks!',
		   'Nixon\'s Head: In our darkest hour, we can stand erect, with proud upthrust bosoms. Fry: Anyone who laughs is a communist!',
		   'Old Man Waterfall: Son, to me, a robot\'s just a garbage can with sparks coming out of it. Bender: [sadly] The sparks keep me warm.',
		   'Dr. Zoidberg: Ambassador Mervin, you killed my lawyer! Ambassador Mervin: You\'re welcome.',
		   'Dr. Zoidberg: Do you think that maybe all this oppression is schmutzing up our freedom lesson? Ambassador Mervin: Ah, take a pill, Zoidberg!',
		   'Dr. Zoidberg: That\'s why I love Earth. You can do what you want, and no one makes you feel guilty because no one cares. Fry: We\'re not listening! Dr. Zoidberg: That\'s what I\'m talking about!',
		   'Fry: Hey, wait, I\'m having one of those things.you know, a headache with pictures. Leela: An idea? Fry: Mmm! Mmm hmm!',
		   'Zapp Brannigan: Remember, men, take him alive so there\'s something left to kill.',
		   'Bender: [Auditioning for All My Circuits in a horrible Hispanic accent] I will see adios, Ped-ree. Come Jesus, my faithful, chee-hua-hua. Tonight we eat, goo-ack-a-mole by de\' el ree-oh! Calculon: That was so terrible, I think you gave me cancer!',
		   'Calculon: I\'ve seen better acting from extras in Godzilla movies.',
		   'Network President: "Bite my shiny metal ass" could be a catchphrase.',
		   'Woman: Have you ever been on TV before? Bender: Once, when I took those hostages. Calculon: I saw that, you were good.',
		   'Professor Farnsworth: I\'ll be the judge of who\'s \'cool\'... with my Cool-ometer! [Prof Farnsworth scans Hubert and Dwight.] Professor Farnsworth: Good Lord! I\'m getting a reading of over 50 Mega-Fonzies!',
		   'Leela: Kids don\'t turn rotten just from watching TV. Fry: Yeah. Give a little credit to our public schools.',
		   'Bender: Have you ever tried simply turning off the tv, sitting down with your children and hitting them?',
		   'Bender: Bender must be stopped. I\'ve gone too far. Who does that guy think I am?',
		   'Bender: This angry mob\'s with me.',
		   'Bender: Interesting. No, wait, the other thing: tedious.',
		   'Bender: Fry, I\'m sorry. I should have understood how someone can love an inferior creature, because I love you. Not in the way of the ancient Greeks, but in the way a robot loves a human, a human loves a dog, and occasionally, a gorilla loves a kitty.',
		   'Fry: Bender, this has nothing to do with you! Bender: That\'s impossible!',
		   'Crowd: What do we want? Fry: Fry\'s dog! Crowd:When do we want it? Fry: Fry\'s dog!',
		   'Fry: You can see how I lived before I met you. Bender: You lived before you met me?! Fry: Yeah, lots of people did. Bender: Really?!',
		   '[Bender announces he is going to dive into lava to retrieve Fry\'s fossilized dog.] Professor Farnsworth: I am a professor; why isn\'t anyone listening to me? You can\'t go in because you\'ll melt!',
		   'Scientist: I\'ve got a degree in homeopathic medicine! Civil Defense Van: You\'ve got a degree in baloney!',
		   '[Halley\'s comet is out of ice, leaving no way to stop global warming] Fry: My God! It\'s out of ice! Like some outer space Motel 6! Leela: [gasps] Completely out of ice?! Bender: This could mean the end of the banana daquiri as we know it! [pause] Also life.',
		   'Morbo: Morbo wishes these stalwart nomads peace among the Dutch tulips. Linda: I\'m sure those windmills will keep them cool. Morbo: WINDMILLS DO NOT WORK THAT WAY! GOOD NIGHT!',
		   'Announcer: Thank you all for coming. It is my pleasure to introduce the host of the Kyoto Global Warming Conventions, the Inventor of the Environment, and first Emperor of the Moon, Al Gore!',
		   'Al Gore: I have ridden the mighty moon worm! Fry: Good for him. Al Gore: My fellow Earthicans, as I discuss in my book Earth in the Balance, and the much more popular Harry Potter And The Balance Of Earth, we need to defend our planet against pollution. As well as dark wizards. Dark Wizard: Sure, blame the wizards! Al Gore: That\'s why I\'m offering a bag of moon sapphires to the first person who solves this problem once and for all. Lovely, aren\'t they? Dark Wizard: Sapphires? With those jewels, I could open the Gate of Karrash!',
		   'Bender: Fry, as you know, there are lots of things I\'m willing to kill for.jewels, vengeance, Father O\'Mallee\'s weed-whacker. But at long last I\'ve found something I\'m willing to die for.this mindless turtle. Fry: Bender, this world isn\'t good enough for you. Bender: Not even close. Goodbye everybody! Don\'t touch my stuff after I\'m dead.it\'s booby-trapped!',
		   'Young Professor Farnsworth: We still have one problem though: This robot will never meet emission standards. Mom: Crap spackle! We\'ll just call it a sport utility robot and classify it as a light truck.',
		   'Bender: When I grow up, I want to be a steam shovel!',
		   'Professor Farnsworth: The Fountain Of Aging? Hmm, it is just a legend. Still, they called the Tooth Fairy a legend and now he\'s head of the FBI.',
		   'Professor Farnsworth: I\'ve got to find a way to escape the horrible ravages of youth. Suddenly, I\'m going to the bathroom like clockwork, every three hours. And those jerks at Social Security stopped sending me checks. Now I have to pay them!',
		   'Bender: Much like everything else in life, pumping is just a primitive, degenerate form of bending.',
		   'Heather: Sir, it\'s not necessary or wise to be naked. Professor Farnsworth: You sound just like my tennis instructor.',
		   'Leela: Oh, Lord! Teeth do not belong in your pants, professor. Professor Farnsworth: Well, I can\'t keep them in my mouth, they\'re nuclear-powered!',
		   'Professor Farnsworth: With my last breath.I curse Zoidberg!',
		   'Pazuzu: And that, little one, is how papa got his freedom. Now bonne nuit; bonne nuit to you all!',
		   'Professor Farnsworth: Oh, I don\'t have time for this. I have to go and buy a single piece of fruit with a coupon and then return it, making people wait behind me while I complain. Fry: He still sounds sorta old. Sorta real old.',
		   'Male Nibblonian: Does he not know? Nibbler: He does not know. Female Nibblonian: He knows not? Nibbler: Knows not does he. Nibblonian: Not he knows? Male Nibblonian: Enough! Fry, it is my duty to inform you that the fate of humanity, the fate of our race, indeed the fate of all that exists and all that will exist rests with you. You are the single most important person in the universe. Fry: Oh snap!',
		   'Fry: I did do the nasty in the past-y. Nibblonian: Verily! And that past nastification is what shields you from the brains. You are the last hope of the universe. Fry: So I really am important? How I feel when I\'m drunk is correct? Nibbloninan: Yes, except the Dave Matthews Band doesn\'t rock.',
		   'Brain: [referring to Fry] Detecting trace amounts of mental activity. Possibly a dead weasel or a cartoon viewer.',
		   'Fry: Hey, wait! This thing knows everything, right? Male Nibblonian: Yes, which is why you\'re supposed to be setting off a bomb! Fry: Wait, I can\'t miss this opportunity to learn the answers to some of the bigger questions. Umm, is it true that postage stamp glue is made of. Giant Brain: Correct! Toad mucus. Male Nibblonian: There\'s no time for this! Activate the bomb! Fry: Okay, just one more. Ummm, what really killed the dinosaurs? Giant Brain: Me!',
		   '[Fry has just found out that it was Nibbler who cryogenically froze him, for the greater good.] Nibbler: What\'s one life weighed against an entire universe? Fry: [Tears in eyes] But it was my life!',
		   'Fry: But I know you in the future. I cleaned your poop. Nibbler: Quite possible. We live long and are celebrated poopers.',
		   'Bender: Uh, can people who hate Star Trek leave? Walter Koenig: Good question! Melllvar: No, you have to stay even longer.',
		   'William Shatner: We\'re just pawns in his diabolical game of checkers!',
		   'George Takei: With pleasure. You see, the show was banned after the Star Trek wars. Zapp Brannigan: You mean after the vast migration of Star Wars fans? Nichelle Nichols: No, that was the Star Wars trek.',
		   'Walter Koenig: And when we woke up, we had these bodies. Fry: Say it in Russian! Walter Koenig: [sighs] Ven ve voke up, ve had these wodies. Fry: [delighted] Eeeeee! Now say "nuclear wessels"! Walter Koenig: No!',
		   'Melllvar: [getting autographs from the cast] Could you make it out to Melllvar? Melllvar has three L\'s. George Takei: I think I\'ve been to enough conventions to know how to spell Melllvar.',
		   'Leonard Nemoy: Melllvar, you have to respect your actors. When I directed Star Trehe goose? Where\'s the fish? Elzar: Hey, that\'s what rich people eat. The garbage parts of the food. Dr. Zoidberg: I ate garbag yesterday, and it didn\'t cost me $300!',
		   'Fry: Of course I w up all night. Not because of caffeine, it was insomnia. I couldn\'t stop thinking about coffee.',
		   'Fry: Fancy cigar. Why don\'t you smoke it already?! Puff! Puff! Go-go-go-go-go!!! Bender:u don\'t blow the smoke from such a magnificent stogie in just a\'s face.',
		   'Cop: Better do what he says. He\'s a whale biologist.',
		   '[Morbo\'s wife is adjusting his tie.] Morbo: Stop it, stot\'s fine. I will destroy you!',
		   'Richard Nixon\'s Head: The loot! The loot! The loot is on fire!',
		   'Farnsworth\'s Girlfriend: What\'s wrong, Hubie? Professor: I\'m afraid the face you fell in love with was just a living blob of goop I bought with my tax rebate. (The goop, retaining its face-shape, crawls away.) Farnsworth\'s Girlfriend: Well...as long as we\'re being honest...I also spent my rebate on a crazy treatment. (She removes her belly button ring, and her weight rapidly increases by several hundred pounds.) Professor: My, that certainly is honest. Farnsworth\'s Girlfriend: It\'s better for us just to be honest-you, wrinkled as a prune... Professor: You, fat as the queen of all sea cows. Farnsworth\'s Girlfriend: I love you!',
		   'Ranger Park: Hi. I\'m Ranger Park, the Park Ranger. Fry: I get it!',
		   'Linda: Alien abductions. Until now, a harmless nuisance. But recently they\'ve taken on a sinister dimension as unsuspecting victims are returned without noses. Morbo: The culprits? Shameless poachers, hunting humans without a permit. Linda: The valuable nose, or "human horn", fetches a high price on alien worlds as an aphrodisiac. Morbo: Demand for "human horn" is great, due in part to titillating scenes from depraved alien TV programs too filthy for Earth broadcast. Let\'s watch.',
		   'Fry: It\'s no use. We\'ve been to every scuzzy bazaar in the galaxy.including Pottery Barn.',
		   'Lrrr: Mmmm, this jerked chicken is good. I think I\'ll have Fry\'s lower horn jerked. Bender: It\'s used to it! Whooo!',
		   'Alien: Hey, I\'m a porno-dealing monster. What do I care what you think?',
		   'Bender: Boy, who knew a cooler could also make a handy wang coffin?',
		   'Fry: Bigfoot! He\'s real! I knew it! The Loch Ness Monster\'s book was right!',
		   'Scientist: I have combined the DNA of the world\'s most evil animals to make the most evil creature of them all. Experiment: It turns out it\'s man.',
		   'Robot Devil: Your lyrics lack subtlety! You can\'t just have your characters announce how they feel! That makes me feel angry!',
		   'Bender: I don\'t recall ever fighting Godzilla, but that is so what I would\'ve done!',
		   'Bender: You may have to "metaphorically" make a deal with the "devil." And by "devil," I mean Robot Devil. And by "metaphorically," I mean "get your coat."',
		   'Robot Devil: Well it so happens I\'m in the mood to make a deal with you. Bender: Forget it. You can\'t tempt me. Robot Devil: Really? There\'s nothing you want? Bender: Hmm. I forgot you could tempt me with things I want.',
		   'Fry: Stop being such a baby and chop my hands off!',
		   'Hedonism Bot: Surgery, in an opera? How wonderfully decadent!',
		   'Fry: But I\'ve never written an opera! Hedonism Bot: And I\'ve never heard one! Still, if you can keep me amused through the overture, I will consider it a smashing success.',
		   'Robot Devil: Give me back my hands! These things are always touching me... in places. Fry: Haha, yeah they get around.'
	   );
        $msg=explode(' ',$data->message,2);
        $irc->message(SMARTIRC_TYPE_CHANNEL, $data->channel,$quotes[rand(0,(count($quotes)-0))]);
    }
}
?>
